install! 'cocoapods', :disable_input_output_paths => true

platform :ios, '12.0'
use_frameworks!

workspace 'Sample'
project 'Sample'

target 'Sample' do
    pod 'NRequest', :path => './../'
    pod 'NRequestSwinject', :path => './../'

    target 'SampleTests' do
        inherit! :search_paths

        pod 'Quick'        , '~> 2.1.0', :inhibit_warnings => true
        pod 'Spry'         , '~> 3.2.3', :inhibit_warnings => true
        pod 'Spry+Nimble'  , '~> 3.2.3', :inhibit_warnings => true
        pod 'Nimble'       , '~> 8.0.2', :inhibit_warnings => true
        
        pod 'NRequestTestHelpers', :path => './../', :testspecs => ['Tests']
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['COCOAPODS_PARALLEL_CODE_SIGN'] = 'true'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'true'
    end
  end

  installer.pods_project.root_object.known_regions = ["Base", "en"]
  installer.pods_project.root_object.development_region = "en"
end
