name: Build-Test

on:
  push:
#    branches:
#      - main
    tags:
      - '**'

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.7"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
